project_id = "sfadxlahyfzeirhvdbhf"

[functions.import-csv]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-commands]
verify_jwt = false

[functions.n8n-transactions-webhook]
verify_jwt = false

[functions.extract-receipt-data]
verify_jwt = false
