project_id = "sfadxlahyfzeirhvdbhf"

[functions.import-csv]
verify_jwt = true

[functions.asaas-create-subscription]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-cancel-subscription]
verify_jwt = true

[functions.asaas-get-payment-status]
verify_jwt = true

[functions.n8n-import-csv-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-commands]
verify_jwt = false

[functions.n8n-transactions-webhook]
verify_jwt = false

[functions.extract-receipt-data]
verify_jwt = false
