project_id = "mukmiafnuzbwnuqdtfou"

[functions.account-connected]
verify_jwt = false

[functions.categorize-transactions]
verify_jwt = true

[functions.create-support-ticket]
verify_jwt = false

[functions.import-csv]
verify_jwt = true

[functions.sync-account]
verify_jwt = true

[functions.generate-feedback]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
