project_id = "sfadxlahyfzeirhvdbhf"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.process-receipt]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-commands]
verify_jwt = false
